image: node:lts

pages:
  stage: deploy
  script:
    - mkdir public
    - cp -r *.html public/
    - cp -r CSS public/
    - cp -r js public/
    - cp -r Imagenes public/
  artifacts:
    paths:
      - public
  only:
    - main
